[workspace]
members = [
    "chronicle",
    "chronicle-api",
    "chronicle-broker",
    "chronicle-storage",
    "chronicle-filter",
    "chronicle-cli",
    "chronicle-common"
]
default-members = [
    "chronicle",
]
